export const CRASH_EDGES = Object.freeze([
  "before_allocation_record_write",
  "after_allocation_record_write_before_file_fsync",
  "after_file_fsync_before_directory_fsync",
  "before_launch_intent_write",
  "after_launch_intent_fsync_before_task_create",
  "during_task_create",
  "after_task_create_before_task_created_record",
  "during_prelaunch_identity_check",
  "before_prelaunch_receipt_write",
  "after_prelaunch_receipt_write_before_fsync",
  "after_prelaunch_receipt_fsync_before_transition",
  "before_release_armed_write",
  "after_release_armed_fsync_before_token_send",
  "after_token_send_before_acknowledgement",
  "after_acknowledgement_before_running_fsync",
  "before_closing_fsync",
  "after_closing_before_ingress_close",
  "during_mediator_join",
  "after_ingress_close_before_kill",
  "during_whole_domain_kill",
  "after_kill_before_zero",
  "during_zero_observation",
  "after_zero_before_capture_fsync",
  "after_capture_fsync_before_seals",
  "during_each_seal",
  "after_seals_before_capture_receipt",
  "after_capture_receipt_before_terminal_receipt",
  "after_terminal_receipt_write_before_file_fsync",
  "after_terminal_file_fsync_before_directory_fsync",
]);

export const NATIVE_LINUX_CASES = Object.freeze([
  "clone3_fixed_trampoline_born_in_domain",
  "pre_release_constructor_import_signal_and_loader_denied",
  "double_fork_setsid_new_pgid_signal_ignoring_descendants",
  "attach_during_running_closing_and_tombstone",
  "transient_zero_one_zero_repopulation",
  "retained_stream_writer_before_during_after_ingress_close",
  "mediator_stall_crash_overflow_and_framing_corruption",
  "capture_descriptor_substitution_post_seal_write_and_digest_disagreement",
  "capture_memfd_fsync_and_each_required_seal",
  "root_forbidden_capabilities_group_and_namespace_drift",
  "unexpected_inherited_fd_and_writable_controller",
  "missing_partial_kill_and_malformed_events",
  "queued_signal_before_clone_and_trampoline_boundary",
  "fd_source_alias_and_reserved_destination_permutations",
  "pidfd_getfd_eperm_yama_enosys_esrch_and_timeout",
  "notification_replay_stale_id_two_writer_and_100000_call_census",
  "unlinked_late_alternate_target_bootstrap_entry",
  "target_wrong_context_key_exfiltration_and_first_syscall_violation",
  "target_no_secret_at_exec_post_prctl_addfd_exact_fixed_fd_sequence",
  "target_addfd_inherited_early_wrong_source_wrong_target_existing_duplicate_response_loss_and_stale_id",
  "task_handle_close_reuse_endpoint_direction_and_clone_session_cgroup_substitution",
  "wrong_cgroup_fd_retained_external_writer_and_late_repopulation",
  "prelaunch_divergent_journal_response_loss_and_directory_fsync_failure",
  "closing_and_terminal_after_link_before_directory_fsync_reconciliation",
  "reconcile_reserved_bytes_wrong_directory_rollback_and_unknown_reap",
  "target_policy_process_thread_namespace_network_fd_transfer_refusal",
]);

export const EFFECT_CRASH_EDGES = Object.freeze([
  "before_effect_intent_write",
  "after_effect_intent_write_before_file_fsync",
  "after_effect_intent_file_fsync_before_directory_fsync",
  "after_effect_intent_before_authority_recheck",
  "after_effect_sent_fsync_before_transport_exposure",
  "after_transport_exposure_before_response",
  "after_response_before_confirmation_write",
  "after_confirmation_write_before_file_fsync",
  "after_confirmation_file_fsync_before_state_commit",
  "during_read_only_reconciliation",
]);

export const MUTATION_CASES = Object.freeze([
  ["remove_trampoline_release_barrier", "pre-release exact execution refusal"],
  ["skip_launch_intent_fsync", "crash after task-create ambiguity is UNCONTAINED"],
  ["recover_crash_as_open", "post-intent restart is absorbing UNCONTAINED"],
  ["reopen_descriptor_by_path", "descriptor continuity loss cannot produce SEALED"],
  ["close_ingress_after_kill", "CLOSING ingress order is exact"],
  ["accept_late_capture_write", "late writer cannot change capture bytes"],
  ["continue_after_capture_invariant_failure", "capture failure is absorbing"],
  ["accept_populated_one", "terminal zero is mandatory"],
  ["ignore_transient_repopulation", "zero-one-zero is terminal failure"],
  ["omit_writer_elimination", "retained writer prevents capture seal"],
  ["skip_capture_fsync", "capture fsync is mandatory"],
  ["drop_each_memfd_seal", "all four memfd seals are mandatory"],
  ["hash_alternate_bytes", "receipt digest binds the sealed capture bytes"],
  ["allow_root_or_forbidden_capability", "privilege attestation refuses release"],
  ["accept_unexpected_fd", "complete inherited-FD allowlist is exact"],
  ["effect_omits_target_content_or_idempotency", "effect intent is complete"],
  ["effect_skips_authority_recheck", "authority is checked immediately before send"],
  ["accept_unverified_local_terminal_receipt", "the root-authenticated exact SEALED receipt is mandatory"],
  ["confirm_after_authority_loss", "authority loss after send is durable ambiguity"],
  ["retry_ambiguous_effect", "one-send capability is permanently consumed"],
  ["local_sealed_confirms_remote", "local and remote receipts remain separate"],
  ["add_pid_pgid_proc_or_subreaper_fallback", "process fallback is categorically refused"],
]);

export const LOCAL_EVIDENCE_CLASSIFICATION = Object.freeze({
  establishes: Object.freeze([
    "portable canonical serialization and authenticated receipt tamper detection",
    "portable monotonic journal validation and crash-to-UNCONTAINED recovery",
    "portable admission refusal and privilege/FD policy validation",
    "portable capture ordering model and required proof-field refusal",
    "portable remote-effect ambiguity and retry-ban state logic",
  ]),
  does_not_establish: Object.freeze([
    "clone3 or born-in-domain placement",
    "trampoline syscall or pre-release execution isolation",
    "Linux credentials, namespace or cgroup-v2 identity",
    "cgroup.kill, populated zero or repopulation exclusion",
    "memfd fsync/seal behavior or writer elimination",
    "real remote-provider idempotency or reconciliation",
    "Foundry, worker or deployment integration",
  ]),
});
